GET http://localhost:80/api/public
###


GET http://localhost:80/api/private
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJBam5QZXU5a3pScnBLLVdlRzZ0bSJ9.eyJpc3MiOiJodHRwczovL2Rldi1seHMyY3Z6ZG9jYmUxbmU2LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9wYXBlci1tYW51ZmFjdHVyZSIsImlhdCI6MTcwMTg1NjQyMywiZXhwIjoxNzAxOTQyODIzLCJhenAiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYiIsInNjb3BlIjoicmVhZDptZXNzYWdlcyBhZGQ6bWFudWZhY3R1cmVfbWFjaGluZXMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.tPFd0yoG5RaileoKEZYFrPuLr9ptQ2Nd78KNAAyC43Vf26p9NcIfJlr_PvLHobDzoPy4gmcSzlY3pKHBgt-NYrxIRY_ZY3nEd6fuWkWQTMXNgU9sGgToBFV9DwboFVfbUIMaTIOXhMdaAyGcSIdzyg5R-TEhv81iW2QDbYWOz2hr0j4tniWzLTYlxhvLkevP76pz1NhT16ksKWhP3cwGQRFnoBQ97wzlv0PxTlHNRjbzHG-hmzO0mBoHxHOQ2w1YA9_nWOaEP25arLw7lXiJPMFu9tRAYP4l9kDdelDBklsbnBNlYSetC9dWxY6g8qp2D_Q8SKZj9-ros-veAETOLw
###

GET http://localhost:80/api/private-scoped
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJBam5QZXU5a3pScnBLLVdlRzZ0bSJ9.eyJpc3MiOiJodHRwczovL2Rldi1seHMyY3Z6ZG9jYmUxbmU2LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9wYXBlci1tYW51ZmFjdHVyZSIsImlhdCI6MTcwMTg1NjQyMywiZXhwIjoxNzAxOTQyODIzLCJhenAiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYiIsInNjb3BlIjoicmVhZDptZXNzYWdlcyBhZGQ6bWFudWZhY3R1cmVfbWFjaGluZXMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.tPFd0yoG5RaileoKEZYFrPuLr9ptQ2Nd78KNAAyC43Vf26p9NcIfJlr_PvLHobDzoPy4gmcSzlY3pKHBgt-NYrxIRY_ZY3nEd6fuWkWQTMXNgU9sGgToBFV9DwboFVfbUIMaTIOXhMdaAyGcSIdzyg5R-TEhv81iW2QDbYWOz2hr0j4tniWzLTYlxhvLkevP76pz1NhT16ksKWhP3cwGQRFnoBQ97wzlv0PxTlHNRjbzHG-hmzO0mBoHxHOQ2w1YA9_nWOaEP25arLw7lXiJPMFu9tRAYP4l9kDdelDBklsbnBNlYSetC9dWxY6g8qp2D_Q8SKZj9-ros-veAETOLw
###


GET http://localhost:80/api/private-scoped/add
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJBam5QZXU5a3pScnBLLVdlRzZ0bSJ9.eyJpc3MiOiJodHRwczovL2Rldi1seHMyY3Z6ZG9jYmUxbmU2LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9wYXBlci1tYW51ZmFjdHVyZSIsImlhdCI6MTcwMTg1NjQyMywiZXhwIjoxNzAxOTQyODIzLCJhenAiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYiIsInNjb3BlIjoicmVhZDptZXNzYWdlcyBhZGQ6bWFudWZhY3R1cmVfbWFjaGluZXMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.tPFd0yoG5RaileoKEZYFrPuLr9ptQ2Nd78KNAAyC43Vf26p9NcIfJlr_PvLHobDzoPy4gmcSzlY3pKHBgt-NYrxIRY_ZY3nEd6fuWkWQTMXNgU9sGgToBFV9DwboFVfbUIMaTIOXhMdaAyGcSIdzyg5R-TEhv81iW2QDbYWOz2hr0j4tniWzLTYlxhvLkevP76pz1NhT16ksKWhP3cwGQRFnoBQ97wzlv0PxTlHNRjbzHG-hmzO0mBoHxHOQ2w1YA9_nWOaEP25arLw7lXiJPMFu9tRAYP4l9kDdelDBklsbnBNlYSetC9dWxY6g8qp2D_Q8SKZj9-ros-veAETOLw
###



GET http://localhost:80/api/admin
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJBam5QZXU5a3pScnBLLVdlRzZ0bSJ9.eyJpc3MiOiJodHRwczovL2Rldi1seHMyY3Z6ZG9jYmUxbmU2LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9wYXBlci1tYW51ZmFjdHVyZSIsImlhdCI6MTcwMTg1NjQyMywiZXhwIjoxNzAxOTQyODIzLCJhenAiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYiIsInNjb3BlIjoicmVhZDptZXNzYWdlcyBhZGQ6bWFudWZhY3R1cmVfbWFjaGluZXMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.tPFd0yoG5RaileoKEZYFrPuLr9ptQ2Nd78KNAAyC43Vf26p9NcIfJlr_PvLHobDzoPy4gmcSzlY3pKHBgt-NYrxIRY_ZY3nEd6fuWkWQTMXNgU9sGgToBFV9DwboFVfbUIMaTIOXhMdaAyGcSIdzyg5R-TEhv81iW2QDbYWOz2hr0j4tniWzLTYlxhvLkevP76pz1NhT16ksKWhP3cwGQRFnoBQ97wzlv0PxTlHNRjbzHG-hmzO0mBoHxHOQ2w1YA9_nWOaEP25arLw7lXiJPMFu9tRAYP4l9kDdelDBklsbnBNlYSetC9dWxY6g8qp2D_Q8SKZj9-ros-veAETOLw
###

#Authorization: Bearer
#eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJBam5QZXU5a3pScnBLLVdlRzZ0bSJ9.eyJpc3MiOiJodHRwczovL2Rldi1seHMyY3Z6ZG9jYmUxbmU2LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9wYXBlci1tYW51ZmFjdHVyZSIsImlhdCI6MTcwMTg1NjQyMywiZXhwIjoxNzAxOTQyODIzLCJhenAiOiJzZ0tONmtUZkVjODNPcmpKVUgwbEN2VFNmOXFaVktWYiIsInNjb3BlIjoicmVhZDptZXNzYWdlcyBhZGQ6bWFudWZhY3R1cmVfbWFjaGluZXMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.tPFd0yoG5RaileoKEZYFrPuLr9ptQ2Nd78KNAAyC43Vf26p9NcIfJlr_PvLHobDzoPy4gmcSzlY3pKHBgt-NYrxIRY_ZY3nEd6fuWkWQTMXNgU9sGgToBFV9DwboFVfbUIMaTIOXhMdaAyGcSIdzyg5R-TEhv81iW2QDbYWOz2hr0j4tniWzLTYlxhvLkevP76pz1NhT16ksKWhP3cwGQRFnoBQ97wzlv0PxTlHNRjbzHG-hmzO0mBoHxHOQ2w1YA9_nWOaEP25arLw7lXiJPMFu9tRAYP4l9kDdelDBklsbnBNlYSetC9dWxY6g8qp2D_Q8SKZj9-ros-veAETOLw


GET http://localhost:80/api/public/good/manufacture-machine/maxPrice
###

GET http://localhost:80/api/private
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJBam5QZXU5a3pScnBLLVdlRzZ0bSJ9.eyJpc3MiOiJodHRwczovL2Rldi1seHMyY3Z6ZG9jYmUxbmU2LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdW5oWnNzY0NZanB3Ukl3TkM5WW51c3ViSHVUb0tFNkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly90ZXN0LyIsImlhdCI6MTcwMTc5MzY5MCwiZXhwIjoxNzAxODgwMDkwLCJhenAiOiJhdW5oWnNzY0NZanB3Ukl3TkM5WW51c3ViSHVUb0tFNiIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.TI3q1NLjPXvKHbSyXJ7iUfSIZToyvfUBh9YOdO0yOREOaVmxDd0IdVDOT_OuKOHSe_vum2F4zslS0PnuVTtma7SX3ixwRzwqcdnWBbx85RjlZfRvHYS1We1IZFQtzm3t4p1cYPPQ9o5xsJ2u5eopMMrVpAREaJP1FBLqBP8mN2gUZ6jCdpjiOsUBh3jAzR7-ElNqdVtQj2jdf2EoqdC01QzziNLdflxXPJGn7J68pUuJ0MlCUCQ7yClz04DSwu8N4KUsmi-GRRbiHVVHmiRqN-X4C4njhBWFtpM9477mOC0GkM2roQHSj0WlEgUzDntb14jQPs5r9c0Ea01KqT0iaw
###


POST https://dev-lxs2cvzdocbe1ne6.eu.auth0.com/oauth/token
Content-Type: application/json

{"client_id":"sgKN6kTfEc83OrjJUH0lCvTSf9qZVKVb",
  "client_secret":"hqJ_voADljoS3GWYxGax_JTb5jnOMuK-ZePKSkhImyTKLURsh7C-d0GbZ3CnVdlM",
  "audience":"https://paper-manufacture",
  "grant_type":"client_credentials"
}