---

application:
  client-origin-url: "http://localhost:4040, https://resplendent-buttercream-d77577.netlify.app"


server:
  port: 6060

  error:
    whitelabel:
      enabled: false
    include-message: always

spring:
  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: komunist
    url: jdbc:postgresql://localhost:5432/paper_manufacture

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
      uri: mongodb+srv://makcimkakakakaka:komunist2023@cluster0.euyznd3.mongodb.net/?retryWrites=true&w=majority&appName=AtlasApp&authMechanism=SCRAM-SHA-1

okta:
  oauth2:
    issuer: https://dev-lxs2cvzdocbe1ne6.eu.auth0.com/
    audience: https://paper-manufacture
...