name: Try to deploy spring app

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: [ec2]

    steps:
      - name: check dir
        run: ls && pwd

      - name: stop runned service
        run: sudo systemctl stop pm

      - name: Remove old files
        run: sudo rm -r paper-manufacture

      - name: Clone repository
        run: git clone https://github.com/LiashenkoAndrey/paper-manufacture.git

      - name: give permission to mvnw file
        run: sudo chmod +x /home/admin/actions-runner/_work/paper-manufacture/paper-manufacture/paper-manufacture/mvnw

      - name: Run application
        run: sudo systemctl start pm
