name: Try to deploy spring app


on:
  push:
    branches: [main]


jobs:
#  buildAndPush:
#    runs-on: ubuntu-latest
#    steps:
#      - name: check code
#        uses: actions/checkout@v3
#
#      - name: Install java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: 'maven'
#
#      - name: Maven build
#        run: mvn clean install -DskipTests
#
#      - name: Login to docker hub
#        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
#
#      - name: Build image
#        run: docker build -t liashenkoandrey/paper-manufacture-backend .
#
#      - name: Push image
#        run: docker push liashenkoandrey/paper-manufacture-backend:latest

  cloneAndRun:
#    needs: buildAndPush
    runs-on: [aws-ec2]

    steps:
      - name: check dir
        run: ls && pwd

      - name: stop runned service
        run: sudo systemctl stop pm

      - name: Remove old files
        run: sudo rm -r paper-manufacture

      - name: Clone repository
        run: git clone https://github.com/LiashenkoAndrey/paper-manufacture.git

      - name: give permission to mvnw file
        run: sudo chmod +x paper-manufacture/mvnw

      - name: Run application
        run: sudo systemctl start pm

#      - name: Login to docker hub
#        run: sudo docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
#
#      - name: Pull image
#        run: sudo docker pull liashenkoandrey/paper-manufacture-backend:latest
#
#      - name: Delete an old image
#        run: sudo docker rm -f pm-backend
#
#      - name: Run container
#        run: sudo docker run -d -p 6060:6060 --name pm-backend liashenkoandrey/paper-manufacture-backend:latest