name: Try to deploy spring app


on:
  push:
    branches: [main]


jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Maven build
        run: mvn clean install -DskipTests

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Build image
        run: docker build -t liashenkoandrey/paper-manufacture-backend .

      - name: Push image
        run: docker push liashenkoandrey/paper-manufacture-backend:latest

  deploy:
    needs: buildAndPush
    runs-on: [aws-ec2]

    steps:
      - name: Pull image
        run: sudo docker pull liashenkoandrey/paper-manufacture-backend:latest

      - name: Delete an old image
        run: sudo docker rm -f pm-backend

      - name: Run container
        run: sudo docker run -d -p 6060:6060 -p 5432:5432 --name pm-backend liashenkoandrey/paper-manufacture-backend:latest